
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension firsttris.vscode-jest-runner
code --install-extension GitHub.copilot
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension rangav.vscode-thunder-client
code --install-extension rocketseat.rocketseatreactjs
code --install-extension rocketseat.theme-omni
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension styled-components.vscode-styled-components
code --install-extension toba.vsfire
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension johnpapa.vscode-peacock